# Generated by Django 3.2 on 2022-12-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_auto_20221221_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
