# Generated by Django 3.2 on 2022-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0003_alter_title_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.SmallIntegerField(default=1),
        ),
    ]
