# Generated by Django 3.2 on 2022-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Код для получения JWT токена'),
        ),
    ]
