# Generated by Django 3.2 on 2022-12-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_code',
            new_name='confirmation_code',
        ),
    ]
