# Generated by Django 3.2 on 2022-12-20 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221220_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcodes',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcodes',
            name='user_name',
            field=models.CharField(default='', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя', regex='^[\\w.@+-]+$')], verbose_name='Ник пользователя'),
        ),
    ]
