# Generated by Django 3.2 on 2022-12-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221220_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcodes',
            old_name='user_name',
            new_name='username',
        ),
    ]
