# Generated by Django 3.2 on 2022-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_user_name_emailcodes_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcodes',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
