# Generated by Django 3.2 on 2022-12-20 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_emailcodes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodes',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='emailcodes',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени пользователя', regex='^[\\w.@+-]+$')], verbose_name='Ник пользователя'),
        ),
    ]
