# Generated by Django 3.2 on 2022-12-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20221220_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodes',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='emailcodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
