# Generated by Django 3.2 on 2022-12-29 09:40

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), reviews.validators.max_value_current_year], verbose_name='Год создания'),
        ),
    ]
