# Generated by Django 3.2 on 2022-12-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221229_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ['title']},
        ),
    ]
